volumes:
  db:

services:
  backend:
    build: .
    ports:
      - "80:80"
    volumes:
      - "$PWD/config.json:/app/config.json:ro"
    restart: unless-stopped

  db:
    image: mysql
    volumes:
      - "db:/var/lib/mysql"
    environment:
        MYSQL_ROOT_PASSWORD: "my-secret-pw"
        MYSQL_DATABASE: leaderboard
    restart: unless-stopped
